development:
  adapter: postgresql
  encoding: unicode
  database: when_androids_dream_dev
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: when_androids_dream_test
  host: localhost
